"""updated patient procedure

Revision ID: a33d392b78e7
Revises: 75942a121b60
Create Date: 2025-11-14 17:48:40.401223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33d392b78e7'
down_revision = '75942a121b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_procedures', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_patient_procedure_schedule'), type_='unique')
        batch_op.create_unique_constraint('uq_patient_procedure_schedule', ['patient_id', 'scheduled_date'])
        batch_op.drop_column('procedure_code')
        batch_op.drop_column('procedure_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('procedure_code', sa.VARCHAR(length=25), nullable=True))
        batch_op.drop_constraint('uq_patient_procedure_schedule', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_patient_procedure_schedule'), ['patient_id', 'procedure_code', 'scheduled_date'])

    # ### end Alembic commands ###
