"""updated patient procedure and procedures foreign keys

Revision ID: 75942a121b60
Revises: 96847c4c4acf
Create Date: 2025-11-14 17:37:01.662965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75942a121b60'
down_revision = '96847c4c4acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('procedure_code_fk'), type_='foreignkey')
        batch_op.create_foreign_key('patient_procedure_to_procedures_fk', 'procedures', ['procedure_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_procedures', schema=None) as batch_op:
        batch_op.drop_constraint('patient_procedure_to_procedures_fk', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('procedure_code_fk'), 'procedures', ['procedure_code'], ['procedure_code'])
        batch_op.drop_column('procedure_id')

    # ### end Alembic commands ###
