"""changed columns in patients table

Revision ID: 96847c4c4acf
Revises: 
Create Date: 2025-10-24 17:30:50.485935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96847c4c4acf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heart_rate_bpm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temperature_celsius', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('respiratory_rate_breaths_per_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oxygen_saturation_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hemoglobin_gL', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hematocrit_LL', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bun_mmolL', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('glucose_mmolL', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pt_seconds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ptt_seconds', sa.Float(), nullable=True))
        batch_op.alter_column('platelet_count',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('white_blood_cell_count',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('creatinine',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('pt')
        batch_op.drop_column('oxygen_saturation')
        batch_op.drop_column('temperature')
        batch_op.drop_column('respiratory_rate')
        batch_op.drop_column('bun')
        batch_op.drop_column('hematocrit')
        batch_op.drop_column('glucose')
        batch_op.drop_column('heart_rate')
        batch_op.drop_column('hemoglobin')
        batch_op.drop_column('ptt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ptt', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hemoglobin', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('glucose', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hematocrit', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('bun', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('respiratory_rate', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('oxygen_saturation', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pt', sa.FLOAT(), nullable=True))
        batch_op.alter_column('creatinine',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('white_blood_cell_count',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('platelet_count',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('ptt_seconds')
        batch_op.drop_column('pt_seconds')
        batch_op.drop_column('glucose_mmolL')
        batch_op.drop_column('bun_mmolL')
        batch_op.drop_column('hematocrit_LL')
        batch_op.drop_column('hemoglobin_gL')
        batch_op.drop_column('oxygen_saturation_percent')
        batch_op.drop_column('respiratory_rate_breaths_per_min')
        batch_op.drop_column('temperature_celsius')
        batch_op.drop_column('heart_rate_bpm')

    # ### end Alembic commands ###
