"""better naming conventions in procedures

Revision ID: ccdade980e4e
Revises: a33d392b78e7
Create Date: 2025-11-30 22:06:54.314984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdade980e4e'
down_revision = 'a33d392b78e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('insurance',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('allergies',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('procedure_planning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_procedure_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_procedure_planning_procedure_id'), type_='unique')
        batch_op.create_unique_constraint('uq_procedure_planning_patient_procedure_id', ['patient_procedure_id'])
        batch_op.drop_constraint(batch_op.f('patient_procedure_checklist_fk'), type_='foreignkey')
        batch_op.create_foreign_key('patient_procedure_checklist_fk', 'patient_procedures', ['patient_procedure_id'], ['id'])
        batch_op.drop_column('procedure_id')

    with op.batch_alter_table('sign_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_procedure_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_sign_in_procedure_id'), type_='unique')
        batch_op.create_unique_constraint('uq_sign_in_patient_procedure_id', ['patient_procedure_id'])
        batch_op.drop_constraint(batch_op.f('patient_procedure_sign_in_fk'), type_='foreignkey')
        batch_op.create_foreign_key('patient_procedure_sign_in_fk', 'patient_procedures', ['patient_procedure_id'], ['id'])
        batch_op.drop_column('procedure_id')

    with op.batch_alter_table('sign_out', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_procedure_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_sign_out_procedure_id'), type_='unique')
        batch_op.create_unique_constraint('uq_sign_out_patient_procedure_id', ['patient_procedure_id'])
        batch_op.drop_constraint(batch_op.f('patient_procedure_sign_out_fk'), type_='foreignkey')
        batch_op.create_foreign_key('patient_procedure_sign_out_fk', 'patient_procedures', ['patient_procedure_id'], ['id'])
        batch_op.drop_column('procedure_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_out', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('patient_procedure_sign_out_fk', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('patient_procedure_sign_out_fk'), 'patient_procedures', ['procedure_id'], ['id'])
        batch_op.drop_constraint('uq_sign_out_patient_procedure_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_sign_out_procedure_id'), ['procedure_id'])
        batch_op.drop_column('patient_procedure_id')

    with op.batch_alter_table('sign_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('patient_procedure_sign_in_fk', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('patient_procedure_sign_in_fk'), 'patient_procedures', ['procedure_id'], ['id'])
        batch_op.drop_constraint('uq_sign_in_patient_procedure_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_sign_in_procedure_id'), ['procedure_id'])
        batch_op.drop_column('patient_procedure_id')

    with op.batch_alter_table('procedure_planning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('patient_procedure_checklist_fk', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('patient_procedure_checklist_fk'), 'patient_procedures', ['procedure_id'], ['id'])
        batch_op.drop_constraint('uq_procedure_planning_patient_procedure_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_procedure_planning_procedure_id'), ['procedure_id'])
        batch_op.drop_column('patient_procedure_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('allergies',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('insurance',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
