name: Backend Flask App Test

on: 
  push:
    branches:
      - backend
  pull_request:
    branches:
      - backend

jobs:
  test:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./backend/

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry (if needed)
        run: |
          poetry config virtualenvs.in-project true

      - name: Install Dependencies with Poetry
        run: |
          poetry install

      - name: Run Tests with Poetry
        run: |
          poetry run python ./tests/test_models.py
