name: Sync Flask RESTX API to Postman

on:
  push:
    branches:
      - main

jobs:
  sync-flask-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask server
      working-directory: backend
      env:
        FLASK_APP: run.py
        FLASK_ENV: development
      run: |
        nohup python -m flask run --host=127.0.0.1 --port=5000 > ../flask.log 2>&1 &
        sleep 10

    - name: Show Flask server logs
      run: cat flask.log || true

    - name: Fetch OpenAPI spec from /swagger.json
      run: |
        curl http://localhost:5000/swagger.json -o openapi.json

    - name: Sync with Postman (Import OpenAPI spec)
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: |
        curl --location --request POST "https://api.getpostman.com/collections/import" \
          --header "X-Api-Key: $POSTMAN_API_KEY" \
          --header "Content-Type: application/json" \
          --data @openapi.json
